server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service-route
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/users/**

          - id: restaurant-public-route
            uri: lb://RESTAURANT-SERVICE
            predicates:
              - Path=/api/restaurants/**

          - id: restaurant-admin-route
            uri: lb://RESTAURANT-SERVICE
            predicates:
              - Path=/api/admin/restaurants/**

          - id: order-public-route
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/orders/**

          - id: order-admin-route
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/admin/orders/**

          - id: coupon-public-route
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/coupons/**

          - id: coupon-admin-route
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/admin/coupons/**

          - id: review-route
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/reviews/**

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-b0rq.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: DEBUG